### ISSUE TITLE
ValueError: fixture percy_snapshot has an unsupported scope value 'package'

### ISSUE THREAD

**Issue by cosmicBboy** [T4rk1n/pytest-dash#7]
I followed the README instructions in the [dash-component-boilerplate repo](https://github.com/plotly/dash-component-boilerplate) and am able to get the app up and running with `python usage.py`, however when I run `pytest tests` I'm getting the following error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 614, in scope2index
INTERNALERROR>     return scopes.index(scope)
INTERNALERROR> ValueError: 'package' is not in list
INTERNALERROR>
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 43, in pytest_sessionstart
INTERNALERROR>     session._fixturemanager = FixtureManager(session)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 981, in __init__
INTERNALERROR>     session.config.pluginmanager.register(self, "funcmanage")
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/config.py", line 255, in register
INTERNALERROR>     ret = super(PytestPluginManager, self).register(plugin, name)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 254, in register
INTERNALERROR>     hook._maybe_apply_history(hookimpl)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 650, in _maybe_apply_history
INTERNALERROR>     res = self._hookexec(self, [method], kwargs)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 1011, in pytest_plugin_registered
INTERNALERROR>     self.parsefactories(plugin, nodeid)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 1132, in parsefactories
INTERNALERROR>     unittest=unittest, ids=marker.ids)
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 738, in __init__
INTERNALERROR>     where=baseid
INTERNALERROR>   File "/Users/nielsbantilan/anaconda3/lib/python3.6/site-packages/_pytest/fixtures.py", line 619, in scope2index
INTERNALERROR>     scope)
INTERNALERROR> ValueError: fixture percy_snapshot has an unsupported scope value 'package'
```

Any ideas on how to debug this? Please let me know if you need more info to reproduce, I exactly followed the README on the dash boilerplate repo.

**Comment by T4rk1n** [comment]
I think it's the version of pytest, `package` fixtures are experimental and problably not in the version you have installed. I'll change the scope of the fixture, in the mean time you can try to update pytest to the latest version. Thanks for the report.

**Comment by cosmicBboy** [comment]
Cool thanks! I updated my version of pytest.

In order to get tests to pass, I had to install the [Chrome driver](https://sites.google.com/a/chromium.org/chromedriver/), add the executable to my `PATH`,
and specify the `--driver` flag when running pytest:

```
pytest tests --driver chrome
```

**Comment by T4rk1n** [comment]
Right I forgot to mention the `--driver` params thanks.
